### PR TITLE
Switch to Visual Studio 2015

### PR DESCRIPTION
**Pull request by Slion**

### CODE REVIEW

**Comment by Slion** [comment]
Could you merge that to make sure we are in sync?

**Comment by Lakritzator** [comment]
You do know that this adds nothing and can be ignored... 😄

**Comment by Slion** [comment]
Well the difference is that it opens the proper VS when you click on the SLN.

**Comment by Slion** [comment]
It looks like your async rework broke the sending of commands.

**Comment by Lakritzator** [comment]
> Well the difference is that it opens the proper VS when you click on the SLN.

ah, I never understood for what it is, I always use the "jump list" on the shortcut on my taskbar :smile:

**Pull request merged**
